// <auto-generated />
using System;
using ExcelFilesCompiler;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelFilesCompiler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241030175356_two")]
    partial class two
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelToCsv.Models.FileDataDto", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("Abo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Agr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BwxNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolHdlCholesterol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DentalDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DentalExam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DentalNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DentalWin")
                        .HasColumnType("int");

                    b.Property<string>("Dna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DodId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ekg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkgNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framingham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullSsn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("G6pd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("G6pdDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("G6pdStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hcg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HearingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HearingProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HearingWin")
                        .HasColumnType("int");

                    b.Property<string>("HepA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HepB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HivNextTestDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HivWin")
                        .HasColumnType("int");

                    b.Property<string>("Hrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LipidNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LipidPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mmr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NearVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Over40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Over44")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanoNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhaDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhaDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhaWin")
                        .HasColumnType("int");

                    b.Property<string>("Pulhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sickle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SickleDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SmId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaskForce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TetTdp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Varicella")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision1mi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vision2pg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisionWin")
                        .HasColumnType("int");

                    b.Property<string>("Vrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FileData");
                });
#pragma warning restore 612, 618
        }
    }
}
