// <auto-generated />
using System;
using ExcelFilesCompiler;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Malama.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929190754_Test13")]
    partial class Test13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Malama.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Malama.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEventUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Malama.Models.ContractDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("COREmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CORFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CORKORank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CORLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CORNotes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CORPhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("CORPhone2")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("CORPrefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ContractAgency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContractClient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContractComponent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ContractID")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContractServiceBranch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DawsonDeputyProgramManagerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DawsonDeputyProgramManagerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DawsonProgramManagerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DawsonProgramManagerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DawsonProjectManagerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DawsonProjectManagerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DawsonRoleOnContract")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("KOEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("KONotes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("KOPhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("KOPhone2")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("KoFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("KoLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ContractDetails");
                });

            modelBuilder.Entity("Malama.Models.EventManagement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AddAddtionalAlternatePoc")
                        .HasColumnType("boolean");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AddtionalAlternatePocEmailPrimary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddtionalAlternatePocEmailSecondary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddtionalAlternatePocFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddtionalAlternatePocLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddtionalAlternatePocPhonePrimary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("AddtionalAlternatePocPhoneSecondary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("AddtionalAlternatePocRank")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddtionalAlternatePocRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompletedSections")
                        .HasColumnType("text");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<string>("Deploy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventAddress1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EventEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventHelpLine")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("EventID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventZipCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("HIVDropOffStaffId")
                        .HasColumnType("bigint");

                    b.Property<string>("HIVSuppliesNeeded")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCEmailPrimary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCEmailSecondary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCPhonePrimary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCPhoneSecondary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("HIVSupplyMilitaryContactPOCRank")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCEmailPrimary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCEmailSecondary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCPhonePrimary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCPhoneSecondary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("ImmVaccineSupplyMilitaryContactPOCRank")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImmunizationVaccineNeeded")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("MOBDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MainPocEmailPrimary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MainPocEmailSecondary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MainPocFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MainPocLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MainPocPhonePrimary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("MainPocPhoneSecondary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("MainPocRank")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PharmacyAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PharmacyAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PharmacyCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PharmacyMilitaryArrangement")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("PharmacyName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PharmacyPhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("PharmacyState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PharmacyZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuestPickupAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuestPickupAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuestPickupCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuestPickupState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuestPickupZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegardingSites")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SecondaryPocEmailPrimary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryPocEmailSecondary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryPocFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryPocLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryPocPhonePrimary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SecondaryPocPhoneSecondary")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SecondaryPocRank")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingAddressCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShippingAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShippingAddressState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingAddressZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan?>("ShippingPocCloseAt")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("ShippingPocDeliveryFromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ShippingPocDeliveryToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ShippingPocEventSetupDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan?>("ShippingPocEventSetupTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShippingPocFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingPocInstruction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ShippingPocLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingPocLocationSecured")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ShippingPocLockableRefrigerator")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<TimeSpan?>("ShippingPocOpenAt")
                        .HasColumnType("interval");

                    b.Property<string>("ShippingPocParkingInstructions")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("ShippingPocPickupDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan?>("ShippingPocPickupTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShippingPocPrimaryEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingPocPrimaryPhone")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("ShippingPocRank")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingPocRefrigeratorAvailable")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ShippingPocSecondaryEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingPocSecondaryPhone")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("ShippingPocSpecialGateInstructions")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ShippingPocSuggestedHourlyFlow")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingPocTablesAndChairsAvailable")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("text");

                    b.Property<string>("SubEventID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalRequestedServiceMembers")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("EventManagement");
                });

            modelBuilder.Entity("Malama.Models.EventManagementStaffAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AvailabilityDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("EventStaffDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventStaffDetailId");

                    b.ToTable("EventManagementStaffAvailability");
                });

            modelBuilder.Entity("Malama.Models.EventManagementTaskforces", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventManagementId")
                        .HasColumnType("bigint");

                    b.Property<string>("Taskforce")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventManagementId");

                    b.ToTable("EventManagementTaskforces");
                });

            modelBuilder.Entity("Malama.Models.EventServiceDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ClientRequestInitial")
                        .HasColumnType("integer");

                    b.Property<long>("EventManagementId")
                        .HasColumnType("bigint");

                    b.Property<string>("EventService")
                        .HasColumnType("text");

                    b.Property<int?>("FinalPreEventConfirmedNumbers")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialReportNumbers")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventManagementId");

                    b.ToTable("EventServiceDetail");
                });

            modelBuilder.Entity("Malama.Models.EventStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ACLSCertDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ACLSCertNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BLSCertDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BLSCertNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BackgroundCheckConcerns")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CACApplicationProcessStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CacExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CredentialingProcessDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DAE")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("DAWSONInternalCredentialingCompleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventOnCallStaff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventOnCallStaffEvent")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("HistoricalCredentialingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NPI")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OnboardingTrainingComplete")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutstandingTrainings")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryAddress1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryZip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryAddress1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecondaryAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecondaryCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryZip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StaffCAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffCellNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("StaffDOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StaffDoDID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StaffID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("StaffInfoEnteredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StaffLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StaffMiddleInitial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StaffPhone2")
                        .HasColumnType("text");

                    b.Property<string>("StaffSSN")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("StaffStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TravelHonorAir")
                        .HasColumnType("boolean");

                    b.Property<bool>("TravelHonorCar")
                        .HasColumnType("boolean");

                    b.Property<bool>("TravelHonorHotel")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventStaff");
                });

            modelBuilder.Entity("Malama.Models.EventStaffDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventManagementId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventStaffId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PreEventAvailability")
                        .HasColumnType("boolean");

                    b.Property<string>("SelectedStation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventManagementId");

                    b.ToTable("EventStaffDetail");
                });

            modelBuilder.Entity("Malama.Models.EventStartEndTimeDayWise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("EventDay")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("EventEndTime")
                        .HasColumnType("interval");

                    b.Property<long>("EventManagementId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan?>("EventStartTime")
                        .HasColumnType("interval");

                    b.Property<int>("ServiceMemberPercentPerDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventManagementId");

                    b.ToTable("EventStartEndTimeDayWise");
                });

            modelBuilder.Entity("Malama.Models.EventWiseStaffRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventStaffDetailId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventStaffDetailId");

                    b.ToTable("EventWiseStaffRole");
                });

            modelBuilder.Entity("Malama.Models.FileDataDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abo")
                        .HasColumnType("text");

                    b.Property<string>("AboNeeded")
                        .HasColumnType("text");

                    b.Property<string>("AboReason")
                        .HasColumnType("text");

                    b.Property<string>("AboStatus")
                        .HasColumnType("text");

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Agr")
                        .HasColumnType("text");

                    b.Property<string>("AudiologistServiceCompleted")
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("BwxNeeded")
                        .HasColumnType("text");

                    b.Property<string>("CheckIn")
                        .HasColumnType("text");

                    b.Property<string>("CheckInBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CheckOut")
                        .HasColumnType("text");

                    b.Property<string>("CheckOutBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CholesterolHdlCholesterol")
                        .HasColumnType("text");

                    b.Property<string>("ClassDentalExam")
                        .HasColumnType("text");

                    b.Property<string>("DentalDue")
                        .HasColumnType("text");

                    b.Property<string>("DentalExam")
                        .HasColumnType("text");

                    b.Property<string>("DentalExamStatus")
                        .HasColumnType("text");

                    b.Property<string>("DentalNeeded")
                        .HasColumnType("text");

                    b.Property<string>("DentalTreatmentReason")
                        .HasColumnType("text");

                    b.Property<string>("DentalTreatmentReceived")
                        .HasColumnType("text");

                    b.Property<int?>("DentalWin")
                        .HasColumnType("integer");

                    b.Property<string>("DentalXrayStatus")
                        .HasColumnType("text");

                    b.Property<string>("Dna")
                        .HasColumnType("text");

                    b.Property<string>("DnaReason")
                        .HasColumnType("text");

                    b.Property<string>("DnaStatus")
                        .HasColumnType("text");

                    b.Property<string>("Dob")
                        .HasColumnType("text");

                    b.Property<string>("DodId")
                        .HasColumnType("text");

                    b.Property<string>("Drc")
                        .HasColumnType("text");

                    b.Property<string>("Ekg")
                        .HasColumnType("text");

                    b.Property<string>("EkgNeeded")
                        .HasColumnType("text");

                    b.Property<string>("EkgNeededReason")
                        .HasColumnType("text");

                    b.Property<string>("EkgNeededStatus")
                        .HasColumnType("text");

                    b.Property<string>("EventDate")
                        .HasColumnType("text");

                    b.Property<string>("EventEndDate")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("FinalDentalClass")
                        .HasColumnType("text");

                    b.Property<string>("FinalTreatmentClass3Reason")
                        .HasColumnType("text");

                    b.Property<string>("Flu")
                        .HasColumnType("text");

                    b.Property<string>("FluNeededStatus")
                        .HasColumnType("text");

                    b.Property<string>("FluReason")
                        .HasColumnType("text");

                    b.Property<string>("Framingham")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("FullSsn")
                        .HasColumnType("text");

                    b.Property<string>("G6pd")
                        .HasColumnType("text");

                    b.Property<string>("G6pdCheckoutStatus")
                        .HasColumnType("text");

                    b.Property<string>("G6pdDate")
                        .HasColumnType("text");

                    b.Property<string>("G6pdReason")
                        .HasColumnType("text");

                    b.Property<string>("G6pdStatus")
                        .HasColumnType("text");

                    b.Property<string>("Hearing")
                        .HasColumnType("text");

                    b.Property<string>("HearingDate")
                        .HasColumnType("text");

                    b.Property<string>("HearingProfile")
                        .HasColumnType("text");

                    b.Property<string>("HearingStatus")
                        .HasColumnType("text");

                    b.Property<int?>("HearingWin")
                        .HasColumnType("integer");

                    b.Property<string>("HepA")
                        .HasColumnType("text");

                    b.Property<string>("HepANeededStatus")
                        .HasColumnType("text");

                    b.Property<string>("HepAReason")
                        .HasColumnType("text");

                    b.Property<string>("HepB")
                        .HasColumnType("text");

                    b.Property<string>("HepBNeededStatus")
                        .HasColumnType("text");

                    b.Property<string>("HepBReason")
                        .HasColumnType("text");

                    b.Property<string>("Hiv")
                        .HasColumnType("text");

                    b.Property<string>("HivBarcode")
                        .HasColumnType("text");

                    b.Property<string>("HivNextTestDate")
                        .HasColumnType("text");

                    b.Property<string>("HivReason")
                        .HasColumnType("text");

                    b.Property<string>("HivStatus")
                        .HasColumnType("text");

                    b.Property<int?>("HivWin")
                        .HasColumnType("integer");

                    b.Property<string>("Hrc")
                        .HasColumnType("text");

                    b.Property<string>("Imm")
                        .HasColumnType("text");

                    b.Property<string>("LabNeeded")
                        .HasColumnType("text");

                    b.Property<string>("Last4")
                        .HasColumnType("text");

                    b.Property<string>("LipidNeeded")
                        .HasColumnType("text");

                    b.Property<string>("LipidPanel")
                        .HasColumnType("text");

                    b.Property<string>("LipidReason")
                        .HasColumnType("text");

                    b.Property<string>("LipidStatus")
                        .HasColumnType("text");

                    b.Property<string>("Mmr")
                        .HasColumnType("text");

                    b.Property<string>("MmrReason")
                        .HasColumnType("text");

                    b.Property<string>("MmrStatus")
                        .HasColumnType("text");

                    b.Property<string>("Mos")
                        .HasColumnType("text");

                    b.Property<string>("Mrc")
                        .HasColumnType("text");

                    b.Property<string>("NearVision")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OptometristServiceCompleted")
                        .HasColumnType("text");

                    b.Property<string>("Over40")
                        .HasColumnType("text");

                    b.Property<string>("Over44")
                        .HasColumnType("text");

                    b.Property<string>("PanoNeeded")
                        .HasColumnType("text");

                    b.Property<string>("PanoramicXray")
                        .HasColumnType("text");

                    b.Property<string>("Pha")
                        .HasColumnType("text");

                    b.Property<string>("PhaDate")
                        .HasColumnType("text");

                    b.Property<string>("PhaDue")
                        .HasColumnType("text");

                    b.Property<string>("PhaFollowUp")
                        .HasColumnType("text");

                    b.Property<string>("PhaStatus")
                        .HasColumnType("text");

                    b.Property<int?>("PhaWin")
                        .HasColumnType("integer");

                    b.Property<string>("PregnancyTestNeeded")
                        .HasColumnType("text");

                    b.Property<string>("Pulhes")
                        .HasColumnType("text");

                    b.Property<string>("Quest")
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Sickle")
                        .HasColumnType("text");

                    b.Property<string>("SickleDate")
                        .HasColumnType("text");

                    b.Property<string>("SickleReason")
                        .HasColumnType("text");

                    b.Property<string>("SickleStatus")
                        .HasColumnType("text");

                    b.Property<long?>("SmId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaskForce")
                        .HasColumnType("text");

                    b.Property<string>("TetTdp")
                        .HasColumnType("text");

                    b.Property<string>("TetTdpNeededStatus")
                        .HasColumnType("text");

                    b.Property<string>("TetTdpReason")
                        .HasColumnType("text");

                    b.Property<string>("Uic")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Varicella")
                        .HasColumnType("text");

                    b.Property<string>("VaricellaNeededStatus")
                        .HasColumnType("text");

                    b.Property<string>("VaricellaReason")
                        .HasColumnType("text");

                    b.Property<string>("Vision")
                        .HasColumnType("text");

                    b.Property<string>("Vision1mi")
                        .HasColumnType("text");

                    b.Property<string>("Vision2pg")
                        .HasColumnType("text");

                    b.Property<string>("VisionDate")
                        .HasColumnType("text");

                    b.Property<string>("VisionStatus")
                        .HasColumnType("text");

                    b.Property<int?>("VisionWin")
                        .HasColumnType("integer");

                    b.Property<string>("VitalsStatus")
                        .HasColumnType("text");

                    b.Property<string>("Vrc")
                        .HasColumnType("text");

                    b.Property<string>("WalkInServiceMember")
                        .HasColumnType("text");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "isDeleted");

                    b.ToTable("FileData");
                });

            modelBuilder.Entity("Malama.Models.ImmunizationStation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BloodTransfusionReason")
                        .HasColumnType("text");

                    b.Property<string>("CancerOrImmuneSystemReason")
                        .HasColumnType("text");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FileDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FluExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FluLotNo")
                        .HasColumnType("text");

                    b.Property<string>("FluManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("FluNeeded")
                        .HasColumnType("text");

                    b.Property<string>("FluReason")
                        .HasColumnType("text");

                    b.Property<string>("HadBloodTransfusionOrAntiviralInPastYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HadSeizureOrNervousSystemProblem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HadSeriousReactionAfterVaccination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HasAllergiesReason")
                        .HasColumnType("text");

                    b.Property<string>("HasAllergiesToMedicationFoodVaccineOrLatex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HasCancerOrImmuneSystemProblem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HasLongTermHealthProblem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("HepAExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HepALotNo")
                        .HasColumnType("text");

                    b.Property<string>("HepAManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("HepANeeded")
                        .HasColumnType("text");

                    b.Property<string>("HepAReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HepBExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HepBLotNo")
                        .HasColumnType("text");

                    b.Property<string>("HepBManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("HepBNeeded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HepBReason")
                        .HasColumnType("text");

                    b.Property<string>("ImmuneSuppressionReason")
                        .HasColumnType("text");

                    b.Property<string>("IsPregnantOrCouldBePregnant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsSickToday")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsSickTodayReason")
                        .HasColumnType("text");

                    b.Property<string>("LongTermHealthProblemReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MMRExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MMRLotNo")
                        .HasColumnType("text");

                    b.Property<string>("MMRManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MMRNeeded")
                        .HasColumnType("text");

                    b.Property<string>("MMRReason")
                        .HasColumnType("text");

                    b.Property<bool?>("PregnancyCheckboxSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceivedVaccineInPast4Weeks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceivedVaccineReason")
                        .HasColumnType("text");

                    b.Property<string>("SeizureReason")
                        .HasColumnType("text");

                    b.Property<string>("SeriousReactionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TetTdpExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TetTdpLotNo")
                        .HasColumnType("text");

                    b.Property<string>("TetTdpManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("TetTdpNeeded")
                        .HasColumnType("text");

                    b.Property<string>("TetTdpReason")
                        .HasColumnType("text");

                    b.Property<string>("TookImmuneSuppressingMedicationRecently")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VaricellaExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VaricellaLotNo")
                        .HasColumnType("text");

                    b.Property<string>("VaricellaManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("VaricellaNeeded")
                        .HasColumnType("text");

                    b.Property<string>("VaricellaReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileDataId")
                        .IsUnique();

                    b.ToTable("ImmunizationStation");
                });

            modelBuilder.Entity("Malama.Models.ServiceTypeProvided", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ServiceTypeProvidedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SubContractorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubContractorId");

                    b.ToTable("ServiceTypeProvided");
                });

            modelBuilder.Entity("Malama.Models.StaffAttributeDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("StaffLicenseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffLicenseId");

                    b.ToTable("StaffAttributeDetails");
                });

            modelBuilder.Entity("Malama.Models.StaffContractAffiliation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventStaffId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubContractorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventStaffId");

                    b.ToTable("StaffContractAffiliation");
                });

            modelBuilder.Entity("Malama.Models.StaffLicense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventStaffId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventStaffId");

                    b.ToTable("StaffLicense");
                });

            modelBuilder.Entity("Malama.Models.StaffLicenseDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("LicenseActiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LicenseState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("StaffLicenseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffLicenseId");

                    b.ToTable("StaffLicenseDetails");
                });

            modelBuilder.Entity("Malama.Models.SubContractor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CompanyMainAddress1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyMainAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyMainCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyMainEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyMainFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyMainLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyMainName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyMainPhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("CompanyMainState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyMainZip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<string>("EventEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventPhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("FinanceAddress1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FinanceAddress2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FinanceCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FinanceEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FinanceFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FinanceLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FinancePhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("FinanceState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FinanceZip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SmallBusinessType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SolicitationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrainingEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainingFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainingLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainingPhone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SubContractor");
                });

            modelBuilder.Entity("Malama.Models.TravelHonor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EventStaffId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rewards")
                        .HasColumnType("decimal(6,0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventStaffId");

                    b.ToTable("TravelHonor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Malama.Models.EventManagementStaffAvailability", b =>
                {
                    b.HasOne("Malama.Models.EventStaffDetail", null)
                        .WithMany("AvailabilityDatesList")
                        .HasForeignKey("EventStaffDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.EventManagementTaskforces", b =>
                {
                    b.HasOne("Malama.Models.EventManagement", null)
                        .WithMany("EventManagementTaskforcesList")
                        .HasForeignKey("EventManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.EventServiceDetail", b =>
                {
                    b.HasOne("Malama.Models.EventManagement", null)
                        .WithMany("EventServiceDetailList")
                        .HasForeignKey("EventManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.EventStaffDetail", b =>
                {
                    b.HasOne("Malama.Models.EventManagement", null)
                        .WithMany("EventStaffDetailList")
                        .HasForeignKey("EventManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.EventStartEndTimeDayWise", b =>
                {
                    b.HasOne("Malama.Models.EventManagement", null)
                        .WithMany("EventStartEndTimeDayWiseList")
                        .HasForeignKey("EventManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.EventWiseStaffRole", b =>
                {
                    b.HasOne("Malama.Models.EventStaffDetail", null)
                        .WithMany("EventWiseStaffRoleList")
                        .HasForeignKey("EventStaffDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.ImmunizationStation", b =>
                {
                    b.HasOne("Malama.Models.FileDataDto", "FileData")
                        .WithOne("ImmunizationRecord")
                        .HasForeignKey("Malama.Models.ImmunizationStation", "FileDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileData");
                });

            modelBuilder.Entity("Malama.Models.ServiceTypeProvided", b =>
                {
                    b.HasOne("Malama.Models.SubContractor", null)
                        .WithMany("ServiceTypeProvided")
                        .HasForeignKey("SubContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.StaffAttributeDetails", b =>
                {
                    b.HasOne("Malama.Models.StaffLicense", null)
                        .WithMany("StaffAttributeDetails")
                        .HasForeignKey("StaffLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.StaffContractAffiliation", b =>
                {
                    b.HasOne("Malama.Models.EventStaff", null)
                        .WithMany("StaffContractAffiliation")
                        .HasForeignKey("EventStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.StaffLicense", b =>
                {
                    b.HasOne("Malama.Models.EventStaff", null)
                        .WithMany("StaffLicense")
                        .HasForeignKey("EventStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.StaffLicenseDetails", b =>
                {
                    b.HasOne("Malama.Models.StaffLicense", null)
                        .WithMany("StaffLicenseDetails")
                        .HasForeignKey("StaffLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.TravelHonor", b =>
                {
                    b.HasOne("Malama.Models.EventStaff", null)
                        .WithMany("TravelHonorList")
                        .HasForeignKey("EventStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Malama.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Malama.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Malama.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Malama.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Malama.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Malama.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.EventManagement", b =>
                {
                    b.Navigation("EventManagementTaskforcesList");

                    b.Navigation("EventServiceDetailList");

                    b.Navigation("EventStaffDetailList");

                    b.Navigation("EventStartEndTimeDayWiseList");
                });

            modelBuilder.Entity("Malama.Models.EventStaff", b =>
                {
                    b.Navigation("StaffContractAffiliation");

                    b.Navigation("StaffLicense");

                    b.Navigation("TravelHonorList");
                });

            modelBuilder.Entity("Malama.Models.EventStaffDetail", b =>
                {
                    b.Navigation("AvailabilityDatesList");

                    b.Navigation("EventWiseStaffRoleList");
                });

            modelBuilder.Entity("Malama.Models.FileDataDto", b =>
                {
                    b.Navigation("ImmunizationRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Malama.Models.StaffLicense", b =>
                {
                    b.Navigation("StaffAttributeDetails");

                    b.Navigation("StaffLicenseDetails");
                });

            modelBuilder.Entity("Malama.Models.SubContractor", b =>
                {
                    b.Navigation("ServiceTypeProvided");
                });
#pragma warning restore 612, 618
        }
    }
}
